from dataclasses import dataclass
from pathlib import Path

from moviepy.editor import (
    VideoFileClip,
    CompositeVideoClip,
    TextClip,
    concatenate_videoclips,
    ColorClip,
)

from src.video.generator import VideoClip


@dataclass
class DebateSegment:
    speaker_name: str
    video_clip: VideoClip
    is_pro: bool


class VideoComposer:
    def __init__(
        self,
        resolution: tuple[int, int] = (1280, 720),
        fps: int = 25,
    ):
        self.resolution = resolution
        self.fps = fps

    def compose_debate(
        self,
        segments: list[DebateSegment],
        output_path: Path,
        title: str = "AI Debate",
    ) -> Path:
        clips = []

        intro = self._create_intro(title)
        clips.append(intro)

        for i, segment in enumerate(segments):
            clip = self._process_segment(segment, i + 1)
            clips.append(clip)

        outro = self._create_outro()
        clips.append(outro)

        final = concatenate_videoclips(clips, method="compose")
        final.write_videofile(
            str(output_path),
            fps=self.fps,
            codec="libx264",
            audio_codec="aac",
        )

        for clip in clips:
            clip.close()
        final.close()

        return output_path

    def _create_intro(self, title: str, duration: float = 3.0) -> VideoFileClip:
        bg = ColorClip(size=self.resolution, color=(20, 20, 30), duration=duration)

        title_clip = TextClip(
            title,
            fontsize=60,
            color="white",
            font="Arial-Bold",
        ).set_position("center").set_duration(duration)

        return CompositeVideoClip([bg, title_clip])

    def _create_outro(self, duration: float = 2.0) -> VideoFileClip:
        bg = ColorClip(size=self.resolution, color=(20, 20, 30), duration=duration)

        text = TextClip(
            "Generated by Agents Arguing",
            fontsize=40,
            color="white",
        ).set_position("center").set_duration(duration)

        return CompositeVideoClip([bg, text])

    def _process_segment(
        self,
        segment: DebateSegment,
        segment_num: int,
    ) -> CompositeVideoClip:
        video = VideoFileClip(str(segment.video_clip.path))

        video = video.resize(height=self.resolution[1] * 0.8)

        x_pos = 50 if segment.is_pro else self.resolution[0] - video.w - 50
        video = video.set_position((x_pos, self.resolution[1] * 0.1))

        bg = ColorClip(
            size=self.resolution,
            color=(30, 30, 40),
            duration=video.duration,
        )

        name_color = "#4CAF50" if segment.is_pro else "#f44336"
        name_label = TextClip(
            segment.speaker_name,
            fontsize=36,
            color=name_color,
            font="Arial-Bold",
        ).set_position((x_pos, 20)).set_duration(video.duration)

        stance_label = TextClip(
            "PRO" if segment.is_pro else "CON",
            fontsize=24,
            color=name_color,
        ).set_position((x_pos, 60)).set_duration(video.duration)

        return CompositeVideoClip([bg, video, name_label, stance_label])

    def create_side_by_side(
        self,
        pro_clip: VideoClip,
        con_clip: VideoClip,
        output_path: Path,
    ) -> Path:
        pro_video = VideoFileClip(str(pro_clip.path))
        con_video = VideoFileClip(str(con_clip.path))

        target_height = self.resolution[1] * 0.7
        pro_video = pro_video.resize(height=target_height)
        con_video = con_video.resize(height=target_height)

        gap = 40
        total_width = pro_video.w + con_video.w + gap
        start_x = (self.resolution[0] - total_width) // 2

        pro_video = pro_video.set_position((start_x, self.resolution[1] * 0.15))
        con_video = con_video.set_position(
            (start_x + pro_video.w + gap, self.resolution[1] * 0.15)
        )

        duration = max(pro_video.duration, con_video.duration)
        bg = ColorClip(size=self.resolution, color=(20, 20, 30), duration=duration)

        final = CompositeVideoClip([bg, pro_video, con_video])
        final.write_videofile(str(output_path), fps=self.fps, codec="libx264")

        pro_video.close()
        con_video.close()
        final.close()

        return output_path
